#!/bin/bash
set -euo pipefail

now=$(date +%s)
deploy_dir=/data/backend/$now
git_branch=${1:-master}

echo 'Fetching latest commits from https://github.com/opencalifornia/disclosure-backend.git...'

echo "Deploying into ${deploy_dir}..."
sudo -i -u backend /bin/bash -exc "
  cd /data/git/disclosure-backend && git fetch;
  mkdir -p $deploy_dir;
  git archive origin/${git_branch} | tar xC $deploy_dir;
  source /data/backend/env/bin/activate;
  pip install -r $deploy_dir/requirements.txt;
  pip install uwsgi;
  ln -sf /data/backend/settings_local.py $deploy_dir/disclosure-backend/project/settings_local.py;
  (
    cd $deploy_dir;
    npm install;
    python disclosure-backend/manage.py collectstatic;
  );
  ln -sfT $deploy_dir /data/backend/current;
  sudo /sbin/initctl restart disclosure-backend;
"

echo "Done!"
