#!/bin/bash
set -euo pipefail

now=$(date +%s)
deploy_dir=/data/backend/$now

echo 'Fetching latest commits from https://github.com/opencalifornia/disclosure-backend.git...'

echo "Deploying into ${deploy_dir}..."
sudo -i -u backend /bin/bash -exc "
  cd /data/git/disclosure-backend && git fetch;
  mkdir -p $deploy_dir;
  git archive origin/master | tar xC $deploy_dir;
  source /data/backend/env/bin/activate;
  pip install --exists-action w -r $deploy_dir/requirements.txt;
  pip install uwsgi;
  ln -sf /data/backend/settings_local.py $deploy_dir/disclosure-backend/project/settings_local.py;
  python $deploy_dir/disclosure-backend/manage.py migrate --noinput;
  python $deploy_dir/disclosure-backend/manage.py collectstatic -v1 --noinput;
  ln -sfT $deploy_dir /data/backend/current;
  sudo /sbin/initctl restart disclosure-backend;
"

echo "Done!"
